# Generated by Django 3.1.7 on 2021-04-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StringModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_type', models.CharField(blank=True, max_length=100, null=True)),
                ('string_length', models.IntegerField(blank=True, null=True)),
                ('winding_a', models.IntegerField(blank=True, null=True)),
                ('winding_b', models.IntegerField(blank=True, null=True)),
                ('winding_c', models.IntegerField(blank=True, null=True)),
                ('winding_d', models.IntegerField(blank=True, null=True)),
                ('winding_e', models.IntegerField(blank=True, null=True)),
                ('winding_f', models.IntegerField(blank=True, null=True)),
                ('eye_x', models.IntegerField(blank=True, null=True)),
                ('eye_y', models.IntegerField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('string_amount', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('twist', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
