# pull official base image
FROM python:3.8.3-alpine

WORKDIR /usr/src/backend

ADD ./requirements.txt .

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

RUN pip install --upgrade pip
RUN pip install gunicorn
RUN pip install -r requirements.txt

COPY . .

ENTRYPOINT [ "./wsgi-entrypoint.sh" ]