# Generated by Django 3.1.7 on 2021-04-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArrowModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrow_name', models.CharField(blank=True, max_length=100, null=True)),
                ('arrow_length', models.CharField(blank=True, max_length=100, null=True)),
                ('arrow_amount', models.IntegerField(blank=True, null=True)),
                ('wrap', models.BooleanField(default=False)),
                ('wrap_color', models.CharField(blank=True, max_length=100, null=True)),
                ('vanes_type', models.CharField(blank=True, max_length=100, null=True)),
                ('vanes_length', models.CharField(blank=True, max_length=100, null=True)),
                ('vanes_color', models.CharField(blank=True, max_length=100, null=True)),
                ('point_type', models.CharField(blank=True, max_length=100, null=True)),
                ('point_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('insert_type', models.CharField(blank=True, max_length=100, null=True)),
                ('nock_type', models.CharField(blank=True, max_length=100, null=True)),
                ('nock_color', models.CharField(blank=True, max_length=100, null=True)),
                ('nock_insert_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
