# Generated by Django 3.1.7 on 2021-04-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrowmodel',
            name='point_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
